// <auto-generated />
using System;
using Cinema.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128125155_AddIsActiveToCinemasAndHalls")]
    partial class AddIsActiveToCinemasAndHalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cinemaid")
                        .HasColumnType("int");

                    b.Property<short?>("Halltype")
                        .HasColumnType("smallint");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Rows")
                        .HasColumnType("smallint");

                    b.Property<short?>("Seatsperrow")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Cinemaid");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Agerating")
                        .HasColumnType("smallint");

                    b.Property<string>("Countrycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit");

                    b.Property<string>("Languagecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posterurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateOnly?>("Releasedate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trailerurl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Movieactor", b =>
                {
                    b.Property<int>("Movieid")
                        .HasColumnType("int");

                    b.Property<int>("Actorid")
                        .HasColumnType("int");

                    b.HasKey("Movieid", "Actorid");

                    b.HasIndex("Actorid");

                    b.ToTable("Movieactors");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Moviegenre", b =>
                {
                    b.Property<int>("Movieid")
                        .HasColumnType("int");

                    b.Property<int>("Genreid")
                        .HasColumnType("int");

                    b.HasKey("Movieid", "Genreid");

                    b.HasIndex("Genreid");

                    b.ToTable("Moviegenres");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("Paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("Ticketid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ticketid")
                        .IsUnique()
                        .HasFilter("[Ticketid] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Pricecategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pricecategories");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Hallid")
                        .HasColumnType("int");

                    b.Property<short?>("Rownumber")
                        .HasColumnType("smallint");

                    b.Property<short?>("Seatnumber")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Hallid", "Rownumber", "Seatnumber")
                        .IsUnique()
                        .HasFilter("[Hallid] IS NOT NULL AND [Rownumber] IS NOT NULL AND [Seatnumber] IS NOT NULL");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Endtime")
                        .HasColumnType("datetime2");

                    b.Property<short?>("Format")
                        .HasColumnType("smallint");

                    b.Property<int?>("Hallid")
                        .HasColumnType("int");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Movieid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Hallid");

                    b.HasIndex("Movieid");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Sessionprice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Categoryid")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Sessionid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Sessionid");

                    b.ToTable("Sessionprices");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Bookingtime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Seatid")
                        .HasColumnType("int");

                    b.Property<int?>("Sessionid")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Seatid");

                    b.HasIndex("Userid");

                    b.HasIndex("Sessionid", "Seatid")
                        .IsUnique()
                        .HasFilter("[Sessionid] IS NOT NULL AND [Seatid] IS NOT NULL");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwordhash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Roleid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Roleid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Hall", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("Cinemaid");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Movieactor", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Actor", "Actor")
                        .WithMany("Movieactors")
                        .HasForeignKey("Actorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Infrastructure.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("Movieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Moviegenre", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Infrastructure.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Movieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Payment", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Ticket", "Ticket")
                        .WithOne("Payment")
                        .HasForeignKey("Cinema.Infrastructure.Entities.Payment", "Ticketid");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Seat", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("Hallid");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Session", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("Hallid");

                    b.HasOne("Cinema.Infrastructure.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("Movieid");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Sessionprice", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Pricecategory", "Category")
                        .WithMany("Sessionprices")
                        .HasForeignKey("Categoryid");

                    b.HasOne("Cinema.Infrastructure.Entities.Session", "Session")
                        .WithMany("Sessionprices")
                        .HasForeignKey("Sessionid");

                    b.Navigation("Category");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Ticket", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("Seatid");

                    b.HasOne("Cinema.Infrastructure.Entities.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("Sessionid");

                    b.HasOne("Cinema.Infrastructure.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("Userid");

                    b.Navigation("Seat");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("Cinema.Infrastructure.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Actor", b =>
                {
                    b.Navigation("Movieactors");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Cinema", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Hall", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Pricecategory", b =>
                {
                    b.Navigation("Sessionprices");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Session", b =>
                {
                    b.Navigation("Sessionprices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.Ticket", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Cinema.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
